import { Smartphone, Shirt, Home, Sparkles, Dumbbell, Car, BookOpen, Panda, Music, Camera } from "lucide-react";

export const categories = [
    {
        title: "Elektronika",
        href: "/category/electronics",
        icon: Smartphone,
        color: "text-blue-500",
        sub: [
            { title: "Laptopy", href: "/category/electronics/laptops" },
            { title: "Tablety", href: "/category/electronics/tablets" },
            { title: "Audio", href: "/category/electronics/audio" },
            { title: "Gaming", href: "/category/electronics/gaming" },
            { title: "Akcesoria", href: "/category/electronics/accessories" },
            { title: "Smart Home", href: "/category/electronics/smart-home" },
            { title: "Kamery i aparaty", href: "/category/electronics/cameras" },
            { title: "Telewizory", href: "/category/electronics/tvs" },
            { title: "Projektory", href: "/category/electronics/projectors" },
            { title: "Drukarki", href: "/category/electronics/printers" },
            { title: "Monitory", href: "/category/electronics/monitors" },
            { title: "Routery i sieci", href: "/category/electronics/routers" },
            { title: "Drony", href: "/category/electronics/drones" },
            { title: "Wearables", href: "/category/electronics/wearables" },
            { title: "Akcesoria komputerowe", href: "/category/electronics/computer-accessories" },
            { title: "Oprogramowanie", href: "/category/electronics/software" },
            { title: "Nośniki danych", href: "/category/electronics/storage" },
            { title: "Kable i ładowarki", href: "/category/electronics/cables-chargers" },
            { title: "Elektronika samochodowa", href: "/category/electronics/car-electronics" },
            { title: "Audio samochodowe", href: "/category/electronics/car-audio" },
            { title: "Głośniki Bluetooth", href: "/category/electronics/bluetooth-speakers" },
            { title: "Słuchawki", href: "/category/electronics/headphones" },
            { title: "Konsolki i akcesoria", href: "/category/electronics/consoles" },
            { title: "VR i AR", href: "/category/electronics/vr-ar" },
        ],
    },
    {
        title: "Moda",
        icon: Shirt,
        color: "text-pink-500",
        href: "/category/fashion",
        sub: [
            { title: "Odzież męska", href: "/category/fashion/men" },
            { title: "Odzież damska", href: "/category/fashion/women" },
            { title: "Buty", href: "/category/fashion/shoes" },
            { title: "Biżuteria", href: "/category/fashion/jewelry" },
            { title: "Torby i dodatki", href: "/category/fashion/accessories" },
            { title: "Bielizna", href: "/category/fashion/underwear" },
        ],
    },
    {
        title: "Dom i Ogród",
        icon: Home,
        color: "text-green-600",
        href: "/category/home",
        sub: [
            { title: "Meble", href: "/category/home/furniture" },
            { title: "Dekoracje", href: "/category/home/decor" },
            { title: "Oświetlenie", href: "/category/home/light" },
            { title: "Narzędzia", href: "/category/home/tools" },
            { title: "Rośliny", href: "/category/home/plants" },
            { title: "Kuchnia", href: "/category/home/kitchen" },
        ],
    },
    {
        title: "Uroda",
        icon: Sparkles,
        color: "text-purple-500",
        href: "/category/beauty",
        sub: [
            { title: "Makijaż", href: "/category/beauty/makeup" },
            { title: "Pielęgnacja", href: "/category/beauty/skincare" },
            { title: "Perfumy", href: "/category/beauty/perfumes" },
            { title: "Włosy", href: "/category/beauty/haircare" },
            { title: "Manicure", href: "/category/beauty/nails" },
            { title: "Higiena osobista", href: "/category/beauty/personal-hygiene" },
        ],
    },
    {
        title: "Sport",
        icon: Dumbbell,
        color: "text-orange-500",
        href: "/category/sport",
        sub: [
            { title: "Fitness", href: "/category/sport/fitness" },
            { title: "Piłka nożna", href: "/category/sport/football" },
            { title: "Kolarstwo", href: "/category/sport/cycling" },
            { title: "Siłownia", href: "/category/sport/gym" },
            { title: "Bieganie", href: "/category/sport/running" },
            { title: "Sporty zimowe", href: "/category/sport/winter" },
        ],
    },
    {
        title: "Motoryzacja",
        icon: Car,
        color: "text-gray-700",
        href: "/category/auto",
        sub: [
            { title: "Części", href: "/category/auto/parts" },
            { title: "Oleje", href: "/category/auto/oils" },
            { title: "Akcesoria", href: "/category/auto/accessories" },
            { title: "Opony", href: "/category/auto/tires" },
            { title: "Motocykle", href: "/category/auto/motorcycles" },
            { title: "Samochody elektryczne", href: "/category/auto/electric-cars" },
        ],
    },
    {
        title: "Książki",
        icon: BookOpen,
        color: "text-indigo-500",
        href: "/category/books",
        sub: [
            { title: "Literatura piękna", href: "/category/books/fiction" },
            { title: "Nauka i edukacja", href: "/category/books/education" },
            { title: "Komiksy", href: "/category/books/comics" },
            { title: "Poradniki", href: "/category/books/guides" },
        ],
    },
    {
        title: "Muzyka",
        icon: Music,
        color: "text-red-500",
        href: "/category/music",
        sub: [
            { title: "CD", href: "/category/music/cd" },
            { title: "Winyle", href: "/category/music/vinyl" },
            { title: "Instrumenty", href: "/category/music/instruments" },
            { title: "Akcesoria muzyczne", href: "/category/music/accessories" },
        ],
    },
    {
        title: "Zwierzęta",
        icon: Panda,
        color: "text-yellow-500",
        href: "/category/pets",
        sub: [
            { title: "Psy", href: "/category/pets/dogs" },
            { title: "Koty", href: "/category/pets/cats" },
            { title: "Akcesoria", href: "/category/pets/accessories" },
            { title: "Karma", href: "/category/pets/food" },
        ],
    },
    {
        title: "Fotografia",
        icon: Camera,
        color: "text-teal-500",
        href: "/category/photography",
        sub: [
            { title: "Aparaty", href: "/category/photography/cameras" },
            { title: "Obiektywy", href: "/category/photography/lenses" },
            { title: "Statywy", href: "/category/photography/tripods" },
            { title: "Akcesoria", href: "/category/photography/accessories" },
        ],
    },

];
